### PR TITLE
Added optional support to build arm images with oem and recovery partitions as part of LVM

### PR DESCRIPTION
**Pull request by venkatnsrinivasan**

### CODE REVIEW

**Review by mudler — APPROVED** [review]
This looks good here, however I didn't tried it locally (yet). changes looks backward compatible too, so we should be good to merge

**Comment by mudler** [comment]
@venkatnsrinivasan at this point the `default.yaml` cloud config file could be saved directly into oem instead of /usr/local when lvm is enabled, wdyt?

**Comment by venkatnsrinivasan** [comment]
> @venkatnsrinivasan at this point the `default.yaml` cloud config file could be saved directly into oem instead of /usr/local when lvm is enabled, wdyt?

We could do that but the script also takes an optional --config file as input, maybe that should go in /oem instead of /usr/local as its doing now, being consistent with userdata in installable systems  ?

**Comment by mudler** [comment]
@venkatnsrinivasan yup sounds good here :+1:

**Pull request merged**
