### PR TITLE
Remove lvm from arm images and use GPT

### PR DESCRIPTION
**Pull request by Itxaka**
Using GPT allows us more than 4 partitions, plus we reduce the complexity.

Also as part of this, it now stores the partitions in the same order as if we were installing, plus allows overriding the default persistent size

### CODE REVIEW

**Comment by Itxaka** [comment]
cc @venkatnsrinivasan

**Comment by Itxaka** [comment]
tested with a build for rpi and seems to work as expected:

```
/dev/loop0: LABEL="COS_ACTIVE" UUID="948006ad-6c1f-43f4-bc42-6232b2a7deed" BLOCK_SIZE="4096" TYPE="ext2"
/dev/sda4: LABEL="COS_STATE" UUID="80e1032b-420e-4ca1-bfe9-079511ba64a8" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="state" PARTUUID="f2d9af52-1c70-417d-b0a7-7b7fcda551c5"
/dev/sda2: LABEL="COS_OEM" UUID="b237896b-7c6c-4635-b2bb-8ce7c188bdf2" BLOCK_SIZE="1024" TYPE="ext4" PARTLABEL="oem" PARTUUID="d39ab0b6-3d66-4823-aed9-5dd3175b25ca"
/dev/sda5: LABEL="COS_PERSISTENT" UUID="690548d3-fad1-4d4a-8826-50b3f750a7a8" BLOCK_SIZE="1024" TYPE="ext4" PARTLABEL="persistent" PARTUUID="98090109-de28-4589-a944-f6eb774916e4"
/dev/sda3: LABEL="COS_RECOVERY" UUID="057dc084-4b6a-40bb-a81c-34a993fc70f4" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="recovery" PARTUUID="91790c81-0ae5-49f3-a031-8d96a2b53fce"
/dev/sda1: LABEL_FATBOOT="COS_GRUB" LABEL="COS_GRUB" UUID="F105-16BF" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI" PARTUUID="589bbdc0-811e-4214-9900-fb2774eb4a67"

```

**Comment by mudler** [comment]
does this work for rpi4 and rpi3 ? I don't remember now if the use of MBR comes from old scripts for previous RPI versions, but probably worth checking if this breaks rpi3

**Review by mauromorales — APPROVED** [review]
great! ... happy that we won't be dealing with loop devices 😅

**Comment by Itxaka** [comment]
> does this work for rpi4 and rpi3 ? I don't remember now if the use of MBR comes from old scripts for previous RPI versions, but probably worth checking if this breaks rpi3

Mmmh, no idea I only got an rpi4.

Do you have an rpi3 to test this? Cc@mauromorales maybe?

**Comment by mauromorales** [comment]
@Itxaka I do, will dust it off and test it out

**Comment by mauromorales** [comment]
Actually not sure if it's a 3 or a 2 LOL, but will check and let you know

**Comment by Itxaka** [comment]
Actually I just read that rpi3 does not read gpt 😭

**Pull request closed without merging**
